### ISSUE TITLE
希望可以增加token或者cookie的方式让swagger.json可以访问

### ISSUE THREAD

**Issue by xcsweb** [findxc/swagger2mock#2]
我现在的swagger.json受到后端的权限控制，无法使用该命令
npx @findtools/swagger2mock --url 
希望可以增加token或者cookie的方式能让授权成功，从而起作用，或者直接使用json文件

**Comment by findxc** [comment]
@xcsweb 增加了使用本地 swagger.json 的方式，命令示例： `npx @findtools/swagger2mock@latest --path mock/swagger.json` ，使用中如果遇到其它问题欢迎继续补充。
